# Generated by Django 3.1.2 on 2021-06-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
    ]
