# Generated by Django 3.1.2 on 2021-06-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_ordermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
